2023-09-05 17:36:17,609 [START] INFO => Process started by diana.s. Args: ['D:\\RPA\\template\\p000_main.py', 'true', 'private_key.pem']

* params: None    
* function duration: None            | * time elapsed: None           
* success:None    
* output: None    


2023-09-05 17:36:17,631 [P001_PROJECT_SETUP] [T01_PROJECT_SETUP]  INFO => Project Setup

* params: []      
* function duration: 0.019900s       | * time elapsed: 0.358419s      
* success: true   
* output: COnfiguração realizda.


2023-09-05 17:40:03,61 [P001_PROJECT_SETUP] [T02_CREATE_JIRA_INSTANCE]  ERROR => None

* params: []      
* function duration: 225.427967s     | * time elapsed: 225.787126s    
* success: false  
* output: Exception
Python 3.11.4: d:\RPA\template\venv-template\Scripts\python.exe
Tue Sep  5 17:40:02 2023

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 D:\RPA\template\Assets\Libraries\RPA\logger.py in inner(*args=(), **kwargs={})
  100                             raise Exception(excpt)
builtinException = <class 'Exception'>
excpt = 'T02_Create_Jira_Instance não retorna um dos segu...ributos obrigatórios: success, logOutput or data.'
Exception: T02_Create_Jira_Instance não retorna um dos seguintes atributos obrigatórios: success, logOutput or data.
    __cause__ = None
    __class__ = <class 'Exception'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of Exception object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of Exception object>
    __doc__ = 'Common base class for all non-exit exceptions.'
    __eq__ = <method-wrapper '__eq__' of Exception object>
    __format__ = <built-in method __format__ of Exception object>
    __ge__ = <method-wrapper '__ge__' of Exception object>
    __getattribute__ = <method-wrapper '__getattribute__' of Exception object>
    __getstate__ = <built-in method __getstate__ of Exception object>
    __gt__ = <method-wrapper '__gt__' of Exception object>
    __hash__ = <method-wrapper '__hash__' of Exception object>
    __init__ = <method-wrapper '__init__' of Exception object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of Exception object>
    __lt__ = <method-wrapper '__lt__' of Exception object>
    __ne__ = <method-wrapper '__ne__' of Exception object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of Exception object>
    __reduce_ex__ = <built-in method __reduce_ex__ of Exception object>
    __repr__ = <method-wrapper '__repr__' of Exception object>
    __setattr__ = <method-wrapper '__setattr__' of Exception object>
    __setstate__ = <built-in method __setstate__ of Exception object>
    __sizeof__ = <built-in method __sizeof__ of Exception object>
    __str__ = <method-wrapper '__str__' of Exception object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    add_note = <built-in method add_note of Exception object>
    args = ('T02_Create_Jira_Instance não retorna um dos segu...ributos obrigatórios: success, logOutput or data.',)
    with_traceback = <built-in method with_traceback of Exception object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "D:\RPA\template\Assets\Libraries\RPA\logger.py", line 100, in inner
    raise Exception(excpt)
Exception: T02_Create_Jira_Instance não retorna um dos seguintes atributos obrigatórios: success, logOutput or data.



NoneType: None
2023-09-05 17:40:03,84 [E00_GENERAL_ERROR] [E01_SEND_ERROR_REPORT]  ERROR => Send error e-mail

* params: ['\n<body bgcolor="#f0f0f8">\n<table width="100%" cellspacing=0 cellpadding=2 border=0 summary="heading">\n<tr bgcolor="#6622aa">\n<td valign=bottom>&nbsp;<br>\n<font color="#ffffff" face="helvetica, arial">&nbsp;<br>\n<big><big><strong>Exception</strong></big></big></font></td>\n<td align=right valign=bottom>\n<font color="#ffffff" face="helvetica, arial">Python 3.11.4: d:\\RPA\\template\\venv-template\\Scripts\\python.exe<br>Tue Sep  5 17:40:03 2023</font></td>\n</tr></table>\n<p>A problem occurred in a Python script.  Here is the sequence of\nfunction calls leading up to the error, in the order they occurred.</p>\n<table width="100%" cellspacing=0 cellpadding=0 border=0>\n<tr><td bgcolor="#d8bbff"><big>&nbsp;</big><a href="file://D:\\RPA\\template\\p000_main.py">D:\\RPA\\template\\p000_main.py</a> in <strong>&lt;module&gt;</strong></td></tr>\n<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;&nbsp;&nbsp;9</small>&nbsp;try:<br>\n</tt></font></td></tr>\n<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;&nbsp;10</small>&nbsp;<br>\n</tt></font></td></tr>\n<tr><td bgcolor="#ffccee"><tt>=&gt;<small>&nbsp;&nbsp;&nbsp;11</small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;P001_Project_Setup()<br>\n</tt></td></tr>\n<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;&nbsp;12</small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>\n</tt></font></td></tr>\n<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;&nbsp;13</small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;jira_issues&nbsp;=&nbsp;P002_Get_Jira_Issues()<br>\n</tt></font></td></tr>\n<tr><td><small><font color="#909090"><strong>P001_Project_Setup</strong>&nbsp;= &lt;class \'p001_project_setup.P001_Project_Setup\'&gt;</font></small></td></tr></table>\n<table width="100%" cellspacing=0 cellpadding=0 border=0>\n<tr><td bgcolor="#d8bbff"><big>&nbsp;</big><a href="file://D:\\RPA\\template\\p001_project_setup.py">D:\\RPA\\template\\p001_project_setup.py</a> in <strong>__new__</strong>(self=&lt;class \'p001_project_setup.P001_Project_Setup\'&gt;)</td></tr>\n<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;&nbsp;18</small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>\n</tt></font></td></tr>\n<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;&nbsp;19</small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.T01_Project_Setup()<br>\n</tt></font></td></tr>\n<tr><td bgcolor="#ffccee"><tt>=&gt;<small>&nbsp;&nbsp;&nbsp;20</small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;self.T02_Create_Jira_Instance()<br>\n</tt></td></tr>\n<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;&nbsp;21</small>&nbsp;<br>\n</tt></font></td></tr>\n<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;&nbsp;22</small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;def&nbsp;T01_Project_Setup():<br>\n</tt></font></td></tr>\n<tr><td><small><font color="#909090"><strong>self</strong>&nbsp;= &lt;class \'p001_project_setup.P001_Project_Setup\'&gt;, self.<strong>T02_Create_Jira_Instance</strong>&nbsp;= &lt;function RPALogging.Task.&lt;locals&gt;.inner&gt;</font></small></td></tr></table>\n<table width="100%" cellspacing=0 cellpadding=0 border=0>\n<tr><td bgcolor="#d8bbff"><big>&nbsp;</big><a href="file://D:\\RPA\\template\\Assets\\Libraries\\RPA\\logger.py">D:\\RPA\\template\\Assets\\Libraries\\RPA\\logger.py</a> in <strong>inner</strong>(*args=(), **kwargs={})</td></tr>\n<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;139</small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>\n</tt></font></td></tr>\n<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;140</small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#propaga&nbsp;a&nbsp;exceçao<br>\n</tt></font></td></tr>\n<tr><td bgcolor="#ffccee"><tt>=&gt;<small>&nbsp;&nbsp;141</small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;raise&nbsp;error&nbsp;<br>\n</tt></td></tr>\n<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;142</small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;else:<br>\n</tt></font></td></tr>\n<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;143</small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#loga&nbsp;a&nbsp;execuçao<br>\n</tt></font></td></tr>\n<tr><td><small><font color="#909090"><strong>error</strong>&nbsp;= Exception(\'T02_Create_Jira_Instance não retorna ...butos obrigatórios: success, logOutput or data.\')</font></small></td></tr></table>\n<table width="100%" cellspacing=0 cellpadding=0 border=0>\n<tr><td bgcolor="#d8bbff"><big>&nbsp;</big><a href="file://D:\\RPA\\template\\Assets\\Libraries\\RPA\\logger.py">D:\\RPA\\template\\Assets\\Libraries\\RPA\\logger.py</a> in <strong>inner</strong>(*args=(), **kwargs={})</td></tr>\n<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;&nbsp;98</small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;result[\'success\']&nbsp;=&nbsp;False<br>\n</tt></font></td></tr>\n<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;&nbsp;99</small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;excpt&nbsp;=&nbsp;f\'{f.__name__}&nbsp;não&nbsp;retorna&nbsp;um&nbsp;dos&nbsp;seguintes&nbsp;atributos&nbsp;obrigatórios:&nbsp;success,&nbsp;logOutput&nbsp;or&nbsp;data.\'<br>\n</tt></font></td></tr>\n<tr><td bgcolor="#ffccee"><tt>=&gt;<small>&nbsp;&nbsp;100</small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;raise&nbsp;Exception(excpt)<br>\n</tt></td></tr>\n<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;101</small>&nbsp;<br>\n</tt></font></td></tr>\n<tr><td><font color="#909090"><tt>&nbsp;&nbsp;<small>&nbsp;&nbsp;102</small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;except&nbsp;Exception&nbsp;as&nbsp;e:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#&nbsp;em&nbsp;caso&nbsp;de&nbsp;exceçao,&nbsp;adiciona&nbsp;os&nbsp;dados&nbsp;da&nbsp;exceçao&nbsp;no&nbsp;log<br>\n</tt></font></td></tr>\n<tr><td><small><font color="#909090"><em>builtin</em> <strong>Exception</strong>&nbsp;= &lt;class \'Exception\'&gt;, <strong>excpt</strong>&nbsp;= \'T02_Create_Jira_Instance não retorna um dos segu...ributos obrigatórios: success, logOutput or data.\'</font></small></td></tr></table><p><strong>Exception</strong>: T02_Create_Jira_Instance não retorna um dos seguintes atributos obrigatórios: success, logOutput or data.\n<br><tt><small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</small>&nbsp;</tt>add_note&nbsp;=\n&lt;built-in method add_note of Exception object&gt;\n<br><tt><small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</small>&nbsp;</tt>args&nbsp;=\n(\'T02_Create_Jira_Instance não retorna um dos segu...ributos obrigatórios: success, logOutput or data.\',)\n<br><tt><small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</small>&nbsp;</tt>with_traceback&nbsp;=\n&lt;built-in method with_traceback of Exception object&gt;\n\n\n<!-- The above is a description of an error in a Python program, formatted\n     for a web browser because the \'cgitb\' module was enabled.  In case you\n     are not reading this in a web browser, here is the original traceback:\n\nTraceback (most recent call last):\n  File "D:\\RPA\\template\\p000_main.py", line 11, in &lt;module&gt;\n    P001_Project_Setup()\n  File "D:\\RPA\\template\\p001_project_setup.py", line 20,', 'Traceback (most recent call last):\n  File "D:\\RPA\\template\\p000_main.py", line 11, in <module>\n    P001_Project_Setup()\n  File "D:\\RPA\\template\\p001_project_setup.py", line 20, in __new__\n    self.T02_Create_Jira_Instance()\n  File "D:\\RPA\\template\\Assets\\Libraries\\RPA\\logger.py", line 141, in inner\n    raise error\n  File "D:\\RPA\\template\\Assets\\Libraries\\RPA\\logger.py", line 100, in inner\n    raise Exception(excpt)\nException: T02_Create_Jira_Instance não retorna um dos seguintes atributos obrigatórios: success, logOutput or data.\n']
* function duration: 0.014069s       | * time elapsed: 225.810364s    
* success: false  
* output: AttributeError
Python 3.11.4: d:\RPA\template\venv-template\Scripts\python.exe
Tue Sep  5 17:40:03 2023

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 D:\RPA\template\Assets\Libraries\RPA\logger.py in inner(*args=('\n<body bgcolor="#f0f0f8">\n<table width="100%" ce...s obrigatórios: success, logOutput or data.\n\n-->\n', 'Traceback (most recent call last):\n  File "D:\\RP...ibutos obrigatórios: success, logOutput or data.\n'), **kwargs={})
   90                         f_result = f(*args, **kwargs)     # tenta executar a chamada da funçao
f_result undefined
f = <function E00_General_Error.E01_Send_Error_Report>
args = ('\n<body bgcolor="#f0f0f8">\n<table width="100%" ce...s obrigatórios: success, logOutput or data.\n\n-->\n', 'Traceback (most recent call last):\n  File "D:\\RP...ibutos obrigatórios: success, logOutput or data.\n')
kwargs = {}

 D:\RPA\template\Events\e000_general.py in E01_Send_Error_Report(error_html='\n<body bgcolor="#f0f0f8">\n<table width="100%" ce...s obrigatórios: success, logOutput or data.\n\n-->\n', traceback='Traceback (most recent call last):\n  File "D:\\RP...ibutos obrigatórios: success, logOutput or data.\n')
   32             Settings.ErrorEmail['receivers'],
global Settings = <class 'Assets.Libraries.cfg.Settings'>
Settings.ErrorEmail undefined
AttributeError: type object 'Settings' has no attribute 'ErrorEmail'
    __cause__ = None
    __class__ = <class 'AttributeError'>
    __context__ = Exception('T02_Create_Jira_Instance não retorna ...butos obrigatórios: success, logOutput or data.')
    __delattr__ = <method-wrapper '__delattr__' of AttributeError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of AttributeError object>
    __doc__ = 'Attribute not found.'
    __eq__ = <method-wrapper '__eq__' of AttributeError object>
    __format__ = <built-in method __format__ of AttributeError object>
    __ge__ = <method-wrapper '__ge__' of AttributeError object>
    __getattribute__ = <method-wrapper '__getattribute__' of AttributeError object>
    __getstate__ = <built-in method __getstate__ of AttributeError object>
    __gt__ = <method-wrapper '__gt__' of AttributeError object>
    __hash__ = <method-wrapper '__hash__' of AttributeError object>
    __init__ = <method-wrapper '__init__' of AttributeError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of AttributeError object>
    __lt__ = <method-wrapper '__lt__' of AttributeError object>
    __ne__ = <method-wrapper '__ne__' of AttributeError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of AttributeError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of AttributeError object>
    __repr__ = <method-wrapper '__repr__' of AttributeError object>
    __setattr__ = <method-wrapper '__setattr__' of AttributeError object>
    __setstate__ = <built-in method __setstate__ of AttributeError object>
    __sizeof__ = <built-in method __sizeof__ of AttributeError object>
    __str__ = <method-wrapper '__str__' of AttributeError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    add_note = <built-in method add_note of AttributeError object>
    args = ("type object 'Settings' has no attribute 'ErrorEmail'",)
    name = 'ErrorEmail'
    obj = <class 'Assets.Libraries.cfg.Settings'>
    with_traceback = <built-in method with_traceback of AttributeError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "D:\RPA\template\p000_main.py", line 11, in <module>
    P001_Project_Setup()
  File "D:\RPA\template\p001_project_setup.py", line 20, in __new__
    self.T02_Create_Jira_Instance()
  File "D:\RPA\template\Assets\Libraries\RPA\logger.py", line 141, in inner
    raise error
  File "D:\RPA\template\Assets\Libraries\RPA\logger.py", line 100, in inner
    raise Exception(excpt)
Exception: T02_Create_Jira_Instance não retorna um dos seguintes atributos obrigatórios: success, logOutput or data.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\RPA\template\Assets\Libraries\RPA\logger.py", line 90, in inner
    f_result = f(*args, **kwargs)     # tenta executar a chamada da funçao
               ^^^^^^^^^^^^^^^^^^
  File "D:\RPA\template\Events\e000_general.py", line 32, in E01_Send_Error_Report
    Settings.ErrorEmail['receivers'],
    ^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'Settings' has no attribute 'ErrorEmail'



Traceback (most recent call last):
  File "D:\RPA\template\p000_main.py", line 11, in <module>
    P001_Project_Setup()
  File "D:\RPA\template\p001_project_setup.py", line 20, in __new__
    self.T02_Create_Jira_Instance()
  File "D:\RPA\template\Assets\Libraries\RPA\logger.py", line 141, in inner
    raise error
  File "D:\RPA\template\Assets\Libraries\RPA\logger.py", line 100, in inner
    raise Exception(excpt)
Exception: T02_Create_Jira_Instance não retorna um dos seguintes atributos obrigatórios: success, logOutput or data.
